version: "3.9"
services:
  user-service:
    build: ./user-server
    ports:
      - "5001:5001"
    environment:
      - DB_URI=mongodb://user-db:27017/userdb
    depends_on:
      - user-db

  post-service:
    build: ./post-server
    ports:
      - "5002:5002"
    environment:
      - DB_URI=mongodb://post-db:27017/postdb
      - MINIO_ENDPOINT=http://minio:9000
      - MINIO_ACCESS_KEY=rootadmin
      - MINIO_SECRET_KEY=rootadmin
      # - MINIO_BUCKET_NAME=post-service-bucket
    depends_on:
      - post-db
      - minio

  notification-service:
    build: ./notification-server
    ports:
      - "5003:5003"
    environment:
      - DB_URI=mongodb://notif-db:27017/notifdb
    depends_on:
      - notif-db

  reverse-proxy:
    image: nginx:alpine
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./reverse-proxy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - user-service
      - post-service
      - notification-service

  # MinIO for object storage
  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data
    ports:
      - "9000:9000"
      - "9001:9001" 
    environment:
      - MINIO_ROOT_USER=rootadmin
      - MINIO_ROOT_PASSWORD=rootadmin
    volumes:
      - minio-data:/data

  # Separate MongoDB containers for each service
  user-db:
    image: mongo:latest
    container_name: user-db
    ports:
      - "27017:27017"
    volumes:
      - user-data:/data/db

  post-db:
    image: mongo:latest
    container_name: post-db
    ports:
      - "27018:27017"
    volumes:
      - post-data:/data/db

  notif-db:
    image: mongo:latest
    container_name: notif-db
    ports:
      - "27019:27017"
    volumes:
      - notif-data:/data/db

volumes:
  user-data:
  post-data:
  notif-data:
  minio-data:
